name: Deploy on VPS

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: git pull then local build and deploy
        run: |
          cd /home/ubuntu/Projets/Odoo-learning/ol_py
          git fetch origin main
          git reset --hard origin/main
          docker compose -f compose.prod.yaml build --no-cache
          docker compose -f compose.prod.yaml up -d --force-recreate --remove-orphans
          docker image prune -f

      - name: Wait for Odoo to be ready
        run: |
          until [ "$(docker inspect -f '{{.State.Health.Status}}' odoo_ol)" = "healthy" ]; do
            echo "Waiting for Odoo..."
            sleep 5
          done

      - name: upgrade Odoo modules
        run: |
          docker exec odoo_ol sh -c '
            odoo \
              -c /etc/odoo/odoo.conf \
              -d odoo \
              -r "$USER" \
              -w "$PASSWORD" \
              --db_host=postgres \
              --db_port=5432 \
              -u all \
              --stop-after-init
          '
